version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: crashtest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  db_data:
